### ISSUE TITLE
Doesn't seem to run

### ISSUE THREAD

**Issue by MrTin** [Eudritch/clean-tauri-sveltekit#2]
Hey - thanks for putting this up! 

I downloaded the repo and tried to run but both in tauri and in the browser all I see is this error:

```
404
Not found: /
Error: Not found: /
    at update (http://localhost:8081/node_modules/@sveltejs/kit/src/runtime/client/client.js:197:12)
    at navigate (http://localhost:8081/node_modules/@sveltejs/kit/src/runtime/client/client.js:997:9)
    at goto (http://localhost:8081/node_modules/@sveltejs/kit/src/runtime/client/client.js:141:11)
    at Object.goto (http://localhost:8081/node_modules/@sveltejs/kit/src/runtime/client/client.js:1064:30)
    at start (http://localhost:8081/@fs/home/ms/projects/clean-tauri-sveltekit/node_modules/@sveltejs/kit/src/runtime/client/start.js:41:19)
    at http://localhost:8081/:16:3
```

Any idea what could be causing this - apologies In advance as I literally just started trying Tauri and Svelte out.

**Comment by Eudritch** [comment]
SvelteKit has a new breaking change in code that I need to refactor. I'm not near a computer right now, but I'll get back to you with a solution later today. 🙂

**Comment by Eudritch** [comment]
I have resolved the issue, and you should now be able to create the next big app with Svelte and Tauri

**Comment by MrTin** [comment]
Managed to figure it out on my own but just tested your repo and it works! 🚀Though I am seeing 500 errors on the Todos page if I just run `yarn run dev`. Oh, and thanks for taking a look at it - I wanted to set it up myself and compare my work to someone that knows what they're doing so it has been helpful.

**Comment by Eudritch** [comment]
I just fixed the todo page, and everything should be working now.
